### ISSUE TITLE
Erroneous "unexpected newline" after super call with no parentheses

### ISSUE THREAD

**Issue by zcoffin86** [chitsaou/vscode-coffeescript-support#4]
I'm not sure if this functionality is deprecated or otherwise discouraged in coffeescript in general, however it seems to still be valid so...

As discussed in various places (such as https://stackoverflow.com/questions/5953670/extend-class-and-pass-all-constructor-arguments-to-super), this is accepted syntax, therefore should not be flagged as a lint error?

![2018-05-24 12_03_42-test coffee - untitled workspace - visual studio code](https://user-images.githubusercontent.com/32465097/40500639-fc874b56-5f4a-11e8-9420-e352310b106e.png)
![2018-05-24 12_03_54-test coffee - untitled workspace - visual studio code](https://user-images.githubusercontent.com/32465097/40500640-fc9ced3a-5f4a-11e8-8507-7902a8b3a11b.png)
http://recordit.co/wwBESnnuUA

**Comment by yorkxin** [comment]
Hi, thanks for your comments. 

This extension doesn't use any linter, instead it uses coffee script parser itself. So any error you see is actually a parse error. In fact, bare `super` was deprecated in CoffeeScript 2: https://coffeescript.org/#breaking-changes-super-extends

I understand that you might not be using the latest CoffeeScript, but currently the extension does not support specifying which CoffeeScript version to use.

As my own projects tend to move to a more recent compiler instead of fixing the tool for legacy versions, unfortunately I can't help you much for now.

**Comment by zcoffin86** [comment]
Ah, thanks for the citation. Strange though, I'm using the latest coffee script (2.3.0) and the arguments are actually passed... I'll update though with the new syntax. Cheers!
